;; -*- lexical-binding: t; -*-

(TeX-add-style-hook
 "capitulo_11"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("report" "12pt" "a4paper")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("inputenc" "utf8") ("fontenc" "T1") ("amsmath" "") ("amssymb" "") ("amsthm" "") ("mathtools" "") ("geometry" "") ("graphicx" "") ("xcolor" "") ("booktabs" "") ("array" "") ("longtable" "") ("multirow" "") ("pgfplots" "") ("tikz" "") ("pgfplotstable" "") ("fancyhdr" "") ("titlesec" "") ("tcolorbox" "") ("enumitem" "") ("hyperref" "") ("cleveref" "") ("caption" "") ("subcaption" "") ("float" "") ("setspace" "") ("parskip" "") ("mathrsfs" "") ("bm" "") ("cancel" "")))
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "report"
    "rep12"
    "inputenc"
    "fontenc"
    "amsmath"
    "amssymb"
    "amsthm"
    "mathtools"
    "geometry"
    "graphicx"
    "xcolor"
    "booktabs"
    "array"
    "longtable"
    "multirow"
    "pgfplots"
    "tikz"
    "pgfplotstable"
    "fancyhdr"
    "titlesec"
    "tcolorbox"
    "enumitem"
    "hyperref"
    "cleveref"
    "caption"
    "subcaption"
    "float"
    "setspace"
    "parskip"
    "mathrsfs"
    "bm"
    "cancel")
   (TeX-add-symbols
    "E"
    "Var"
    "Cov"
    "betahat"
    "uhat"
    "sigmahat"
    "yhat"
    "BLUE"
    "OLS"
    "GLS"
    "WLS"
    "iid"
    "plim")
   (LaTeX-add-labels
    "eq:mlc"
    "eq:homo"
    "eq:homo_matricial"
    "eq:hetero"
    "eq:omega"
    "fig:homo_vs_hetero"
    "eq:park_form"
    "eq:exp_form"
    "eq:linear_sd"
    "eq:glejser_form"
    "fig:patrones_sigma"
    "eq:ols_obj"
    "eq:cpo1"
    "eq:cpo2"
    "eq:beta2hat"
    "eq:insesgadez"
    "eq:sandwich"
    "eq:var_conv"
    "eq:var_beta2_true"
    "eq:var_beta2_conv"
    "fig:pesos_mco_mcg"
    "eq:modelo_original"
    "eq:modelo_transformado"
    "eq:verif_homo"
    "eq:modelo_matricial_trans"
    "eq:var_u_star"
    "eq:gls_estimator"
    "eq:var_gls"
    "eq:wls_obj"
    "eq:wls_cpo1"
    "eq:wls_cpo2"
    "eq:wls_slope"
    "fig:mco_vs_mcg"
    "tab:propiedades"
    "eq:sigma2_hat"
    "eq:e_sigma2"
    "eq:t_stat"
    "fig:residual_plots"
    "eq:park_model"
    "eq:park_log"
    "eq:park_regresion"
    "eq:glejser1"
    "eq:glejser2"
    "eq:glejser3"
    "eq:glejser4"
    "eq:spearman"
    "eq:spearman_t"
    "eq:gq_stat"
    "fig:gq"
    "eq:bpg_pi"
    "eq:bpg_regresion"
    "eq:bpg_stat"
    "eq:white_regresion"
    "eq:white_stat"
    "eq:white_simple"
    "fig:white_flowchart"
    "tab:transformaciones"
    "eq:white_sandwich"
    "eq:log_log"
    "eq:cv_const"
    "eq:mortalidad"
    "eq:mortalidad_ols"
    "fig:mortalidad_residuales"
    "eq:id"
    "fig:id_residuales"
    "eq:beta2_final"
    "eq:beta1_final"
    "fig:eficiencia")
   (LaTeX-add-amsthm-newtheorems
    "teorema"
    "proposicion"
    "corolario"
    "lema"
    "definicion"
    "ejemplo"
    "ejercicio"
    "observacion")
   (LaTeX-add-xcolor-definecolors
    "azuloscuro"
    "azulmedio"
    "azulclaro"
    "rojoalerta"
    "verdematematica"
    "amarillonota"
    "grisclaro"
    "naranjaejemplo"
    "moradoteorema")
   (LaTeX-add-tcolorbox-tcbuselibraries
    "theorems,skins,breakable,most"))
 :latex)

