#+TITLE:  Modelado Diagnostico
#+SUBTITLE: Notas de clase de Econometria UPTC
#+AUTHOR: Emanuel Quintana Silva
#+ORG-REF: Damodar Gujarati
#+DATE: <2026-04-22 Wed>

* Primera parte

La *creacion* de modelos econometricos requiere una comprension profunda y habilidades para especificar correctamente el modelo y realizar pruebas de diagnostico, ya que la busqueda del modelo "correcto" es un desafio constante en la econometria.

La especificacion del modelo es un paso crucial en la creacion de modelos econometricos. Un modelo bien especificado debe cumplr ciertos supuestos, como la linealidad, la independencia
de los errores, la homocedasticidad y la normalidad de los errores. Sin embargo, en la practica, estos supuestos a menudo no se cumplen, lo que puede llevar a errores de especificacion del modelo. Por ejemplo si el modelo no incluye variables relevantes, se puede producir un sesgo en la estimacion de los parametros.

Un enfoque comun para abordar  este problema es utilizar tecnicas de selecccion de variables, como la regresion stepwise o la regresion por pasos, que permiten seleccionar las variables mas relevantes para el modelo. Sin embargo, estas tecnicas tambien pueden ser sensibles a la presencia de multicolinealidad o de variables irrelevantes.


Preguntas que se abordan en el capitulo.

* 1. ¿Que hacer para encontrar el modelo "correcto"? En otras palabras, ¿cuales son los criterios para elegir el modelo a partir del analisis empirico?

* 2. ¿Que tipos de errores de especificacion de modelos son mas comunes en la practica?

* 3. ¿Cuales son las consecuencias de los errores de especificacion?

* 4. ¿Como se detectan los errores de especificacion? En otras palabras, ¿Cuales son algunas herramientas de diagnostico disponibles?

* 5. Una vez detectados los errores de especificacion, ¿CUales son los remedios que se pueden adoptar y con qye beneficios?

* 6. ¿Como se evalua el desempeño de modelos contendientes?


Acontinuacion abordaremos los criterios de selccion del modelo
