#+TITLE: Ejercicio 13.9 Econometria Damodar Gujarati.
#+SUBTITLE: Ejercicio tomado de Damodar Gujarati Econometria.
#+DATE: <2026-05-24 Sun>
#+AUTHOR: Emanuel Quintana Silva.

** Enunciado: /Modelo de asignacion de precios de activos de capital/. El modelo de asignacion de precios de activos de capitañ (CAPM) de la teoria de inversion moderna postula la siguiente relacion entre la tasa de rendimiento promedio de un valor (una accion comun), medida durante un determinado periodo, y la volatilidad del  titulo, relacion denominada /coeficiente Beta/ (la volatilidad es una medida del riesgo):

$$\bar{R_{i}} = \alpha_{1}_{} + \alpha_{2}(\beta_{i}) + u_{i}$$

donde $\bar{R_{i}}$ = Tasa de rendimiento promedio del valor i.
$\beta_{i}$ = Coeficiente Beta verdadero del valor i
$u_{i}$ = Termino de perturbacion estocastico.

La verdadera $\beta_{i}$ no es directamente observable pero se mide de la siguiente manera:

$$r_{it} = \alpha_{1} + \beta^{*}r_{mt} + e_{t}$$

donde $r_{it}$ = Tasa de rendimiento del valor i durante el tiempo t.
$r_{mt}$ = Tasa de rendimiento de mercado durante el tiempo t (esta tasa es la tasa de rendimiento sobre algun indice general del mercado, como el indice S&P).
$e_{t}$ = Termino de residuo.

y donde $\beta^{*}$ es una estimacion del "verdadero" coeficiente beta. En la practica por consiguiente, en lugar de estimar $\bar{R_{i}} = \alpha_{1} + \alpha_{2}(\beta_{i}) + u_{i}$, se estima:

$$\bar{R_{i}} = \alpha_{1} + \alpha_{2}(\beta^{*}_{i}) + u_{i}$$

donde las $\beta_{i}^{*}$ se denominan de la regresion $r_{it} = \alpha_{1} + \beta r_{mt} + e_{t}$, Pero, como las $\beta^{}*_{i}$ son estimadas, la relacion entre la verdadera $\beta$ y $\beta^{*}$ se escribe asi

$$\beta_{i}^{*} = \beta_{i} + v_{i}$$
doden $v_{i}$ se denomina /error de medicion/.

a) ¿Cual sera el efecto de este error de medicion sobre la estimacion de $\alpha_{2}$?

b) ¿El $\alpha_{2}$ estimado de $\bar{R_{i}} = \alpha_{1} + \alpha_{2}(\beta_{i}) + u_{i}$ proporcionarauna estimacion insesgada del verdadero $\alpha_{2}$? De no ser asi, ¿es esta una estimacion consistente de $\alpha_{2}$? De no ser asi, ¿que medidas correctivas sugiere?

** Solucion

Este ejercicio se centra en el problema de los *errores de medicion en la variables explicativas,* un caso particular de error de especificacion en el regresor (en este caso, el coeficiente Beta  estimado $\beta_{i}^{*}$) esta  correlacionado con el termino de error del modelo.

a) *Efecto del error de medicion sonre la estimacion de $\alpha_{2}$.*

   El efecto principal de este error es que el estimador de Minimos Cuadrados Ordinarios (MCO)  de $\alpha_{2}$ sufrira de lo que se conoce como *sesgo de atenuacion.*

   - *Subestimacion del Parametro:* Debido a que el regresor observar $\beta_{i}^{*}$ contiene un error de medicion $v_{i}$, la varianza de la variable independiente se ve "inflado" artificialmente. Esto provoca que el valor estimado de $\alpha_{2}_{}$ sea, en valor absoluto, *menor que el valor veradero* de la relacion entre el riesgo y el rendimiento.
