#+TITLE: Ejercicio 13.4 de el libro de Econometria de Damodar Gujarati
#+SUBTITLE: Este es un ejercicio desarrorado por un estudinate de econometria de la UPTC.
#+DATE <16/05/2026>

* Enunciado Suponga que le "verdadero" modelo es

$$Y_{t} = \beta_{1} + \beta_{2}X_{2t }+ u_{t}$$

pero añadimoos una variable "irrelevante", X3, al modelo (irrelevante en el sentido que el verdadero coeficiente \beta_{3} que acompaña a la variable X_{3} es cero) y estime.

$$Y_{i}_{} + \beta_{1} + \beta_{2}X_{2t} + u_{t}$$

a) ¿$R^{2}$ y $R^{2}$ ajustado para el modelo (2) serian mas grandes que las del modelo (1)?
b) ¿Las estimaciones de \beta_{1} y \beta_{2}, obetenidas de (2) son insesgadas?
c) ¿La inclusion de la variable "irrelevante" X_{3} afecta las varianzas de $\hat{\beta_{1}}$ y $\hat{\beta_{2}}$?

   ** Solucion

   Este esenario se define tecnicamente como *sobreajuste de un modelo* o *inclusion de una variable irrelevante*. A continuacion, se detallan las consecuencias esyadisticas para cada una de las preguntas:

   *a). ¿$R^{2}$ y $R^{2}$ ajustado para el modelo (2) serian mas grandes que las del modelo (1)?*

   - *R^2 convencional*: El valor de $R^{2}$ del modelo (2) sera *mayor o al menos igual* al del modelo (1). Esto es un hecho algebraico: la suma de los residuales cuadrados (SRC) nunca añadir regresores, que signidica que el $R^{2}$ nunca disminuye independientemente de si la variable tienen sentido economico o no.

- *R^2 ajustada (\bar{R\(^{2}\)})*: El valor de $R^{2}$ del modelo (2) sea *menor* que la del modelo (1)
