#+TITLE: Ejercicio 13.9 Econometria Damodar Gujarati.
#+SUBTITLE: Ejercicio tomado de Damodar Gujarati Econometria.
#+DATE: <2026-05-24 Sun>
#+AUTHOR: Emanuel Quintana Silva.

** Enunciado: /Modelo de asignacion de precios de activos de capital/. El modelo de asignacion de precios de activos de capitañ (CAPM) de la teoria de inversion moderna ppostula la siguiente relacion entre la tasa de rendimiento promedio de un valor (una accion comun), medida durante un determinado periodo, y la volatilidad del  titulo, relacion denominada /coeficiente Beta/ (la volatilidad es una medida del riesgo):

$$\bar{R_{i}} = \alpha_{1}_{} + \alpha_{2}(\beta_{i}) + u_{i}$$

donde $\bar{R_{i}}$ = Tasa de rendimiento promedio del valor i.
$\beta_{i}$ = Coeficiente Beta verdadero del valor i
$u_{i}$ = Termino de perturbacion estocastico.

La verdadera $\beta_{i}$ no es directamente observable pero se mide de la siguiente manera:

$$r_{it} = \alpha_{1} + \beta^{*}r_{mt} + e_{t}$$

donde $r_{it}$ = Tasa de rendimiento del valor i durante el tiempo t.
$r_{mt}$ = Tasa de rendimiento de mercado durante el tiempo t (esta tasa es la tasa de rendimiento sobre algun indice general del mercado, como el indice S&P).
$e_{t}$ = Termino de residuo.

y donde $\beta^{*}$ es una estimacion del "verdadero" coeficiente beta. En la practica por consiguiente, en lugar de estimar $\bar{R_{i}} = \alpha_{1} + \alpha_{2}(\beta_{i}) + u_{i}$, se estima:

$$\bar{R_{i}} = \alpha_{1} + \alpha_{2}(\beta^{*}_{i}) + u_{i}$$
