#+TITLE: Analisis de regresion con dos variables: algunas ideas basicas.
#+DATE: <2026-06-09 Tue>

El analisis de regresion con dos variables se enfoca en la relacion entre una variable dependiente y una variable explicativa, con el objetivo de estimar o predecir el valor promedio de la variable dependiente en funcion de los valores conocidos de la variable explicativa.

El analisis de regresion bivariable se puede representar mediante la ecuacion:

$$Y = \beta_{0} + \beta_{1}X + \epsilon$$

donde $Y$ es la variable dependiente, $X$ es la variable ecplicativa, $\beta_{0}$ es ek intercepto, $\beta_{1}$ es el coeficiente de regresion y $\epsilon$ es el error aleatorio. El objetico es encontrar los valores de $\beta_{0}$ y $\beta_{1}$ que minimicen la suma de los cuadrados de los errores.

En el ejemplo hipotetico presentado, se tienen 60 familias con ingresos semanales ($X$) y gastos de consumo semanales ($Y$) en dolares.

La ecuacion de regresion se puede estimar mediante el metodo de los minimos cuadrados, que busca minimizar la suma de los cuadrados de los errores:

$$S = \sum_{}_{i=1}^{n }(Y_{i} - \beta_{0} - \beta_{1}X_{i}_{})^{2}$$

donde $n$ es el numero de observaciones. Al tomar las derivadas parciales de $S$ con respecto a $\beta_{0}$ y $\beta_{1}$ y estabñecerlas iguales a cero, se pueden obtener las ecuaciones normales:

$$\sum_{i=1}^{n} Y_{i} = n\beta_{0} + \beta_{1} \sum_{i=1}^{n} X_{i}$$

$$\sum_{i=1}^{n} X_{i}Y_{i} = \beta_{0} \sum_{i=1}^{n} X_{i} + \beta_{1} \sum_{i=1}^{n} X_{i}^{2}$$

Resolviendo este tema de ecuaciones, se pueden obtener los estimadores de $\beta_{0}$ y $\beta_{1}$.

El analisis de regresion es una tecnica estadistica ampliamente utilizada en diversas disciplinas, como la economia, la sociologia, la psicologia y la medicina. Algunos autores clave en el desarrollo de la regresion lineal son Karl Pearson, Francis Galton y Ronald Fisher. En la actualidad, el analisis de regresion se utiliza en una variedad de aplicaciones, desde la prediccion de resultados en la medicina hasta la evaluacion de politicas economicas.

* Concepto de funcion de regresion (FRP)

La funcion de regresion poblacional (FRP) describe la relacion funcional entre la media condicional de una variable dependiente Y yna variable explicativa X, y se puede representar mediante la ecuacion $E(Y | X_{i}) = f(x_{i})$

La funcion de regresion poblacional se define como la esperanza condicional de la varivale dependiente Y dado un valor especifico de la variable explicativa X, es decir $E(Y | X_{i})$. Esta funcion se puede representar de la siguiente manera:

$$E(Y | X_{i}) = f(X_{i})$$

donde $f(X_{i})$ denota una funcion de la variable explicativa X. Un ejemplo comun es la funcion lineal donde la relacion entre la media condicional y la variable explicativa se puede representar mediante la ecuacion:

$$E(Y | X_{i}) = \beta_{1} + \beta_{2}X_{i}$$

donde  $\beta_{1}$ y $\beta_{2}$ son parametros no conocidos pero fijos decir, depende de la naturaleza de los datos y no se puede determinar a priori. Sin embargo en algunos casos, la teoria puede proporcionar alguna guia sobre la forma que puede adoptar la funcion. Por ejemplo, en economia, se puede supone que el consumo tiene una relacion lineal con el ingreso, lo que lleva a la ecuacion:

$$E(Y | X_{i}) \beta_{1} + \beta_{2}X_{i}$$
donde $Y$ es el consumo y $X_{i}$ es el ingreso.

La funcion de regresion poblacional es un concepto fundamental en la estadistica y la econometria. La idea de modelar la relacion entre variables fue introducida por primera vez por Carl Friedrich Gauss y Pierre-Simon Laplace en el siglo XIX. Sin embargo, no fue hasta el siglo XX que la funcion de regresion poblacional se convirtio en un tema de estudio importante en la estadistica y la econometria.

Algunos autores clave en el desarrollo de la teoria de regresion incluyen:

- Carl Friedrich Gauss: quien introdujo el concepto de regresion lineal.
- Pierre-Simon Laplace: quien trabajo en la teoria de la regresion lineal.
- Jan Tinbergen: quien aplico la regresion lineal en la economia y desarrollo la teoria de la regresion multiple.

EL debate actual en la literatura se centra en la seleccion de modleos, la validacion de supuestos y la interpretacion de los resultados. Ademas, la creciente disponibilidad de datos y la capacidad de procesamineto han llevado al desarrollo de nuevos metodos y tecnicas para la regresion, como la regresion no lineal y la regresion conrestricciones.


** Significado del termino lineal

El termino "lineal" en modelos de regresion se interpreta de dos formas: linealidad en las variables explicativas y linealidad en los parametros, siendo esta ultima la pertinente para el desarrollo de la teoria de regresion.

*** Linealidad en las variables

Linealidad es aquel en que la esperanza condicional de /Y/ es una funcion lineal /$X_{n}$/. Geometricamente la curva de regresion en este caso es una recta. En esta interpretacion, una funcion de regresion como $E(Y | X_{i}) = \beta_{1} + \beta_{2}X_{i}^{2}$ no es una funcion lineal porque la variable X aparece elevada a una potencia o indice de 2.

Un ejemplo concreto es el modelo $E(Y|X_{i}) = \beta_{1} + \beta_{2} X_{i}^{2}$. Si $X_{i} = 3$, entonces $E(Y|X_{i}) = \beta_{1} + 9\beta_{2}$, que es una función lineal en $\beta_{1}$ y $\beta_{2}$. Sin embargo, el modelo $E(Y|X_{i}) = \beta_{1} + \beta_{2}^{2} X_{i}$ no es lineal en los parámetros, ya que $E(Y|X_{i} = 3) = \beta_{1} + 3\beta_{2}^{2}$.

En resumen, La linealidad en los parametros es una condicion necesaria para que un modelo de regresion sea considerado lineal. Esto se puede representar esquematicamente como:

- $E(Y|X_i) = \beta_1 + \beta_2 X_i$: lineal en los parámetros y en las variables
- $E(Y|X_i) = \beta_1 + \beta_2 X_i^2$: lineal en los parámetros, pero no lineal en las variables

*** Linealidad en los parametros

Esta se presenta cuando la esperanza condicional de /Y/, $E(Y|X_{i})$, es una funcion lineal de los parametros, los \beta; puede ser o no lineal en la variable /X/. De acuerdo con la interpretacion, /$E(Y|X_{i}) = \beta_{1} + \beta_{2}X_{i}^{2}$/ es un modelode regresion lineal (en el parametro). Para ver lo anterior supongamos que /X/ tiene un valor de 3. Por tanto, /E(Y|X = 3) = \beta_{1} + 9\beta_{2}/, ecuacion a todas luces lineal en $\beta_{1}$ y $\beta_{2}$.
